AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Instance Creation
Mappings:
  Constants:
    AMI:
      DefaultAMIId: ami-032e5b6af8a711f30
      Frontend1: ami-0dec395d17f4a9cb2
      RoutingServerAMI: ami-0ca7a652ad35b1802
      Mongo:  ami-05aacabb70026a020
    Tags:
      environment: Demo Openfleet
Parameters:
  BaseStackName:
    Type: String
    Default: env-Stage
    Description: Parent Stack Name.
  FrontendRoutingInstanceType:
    Type: String
    Default: m5.xlarge
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.large
      - m3.medium
      - m3.large
      - m3.xlarge
      - m4.large
      - m4.xlarge
      - m5.large
      - m5.xlarge
    Description: Enter the instance type for the application server. Default is t2.medium.
  EngineInstanceType:
    Type: String
    Default: m5.large
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.large
      - m3.medium
      - m3.large
      - m3.xlarge
      - m4.large
      - m4.xlarge
      - m5.large
      - m5.xlarge
    Description: Enter the instance type for the application server. Default is t2.medium.
  MongoInstanceType:
    Type: String
    Default: m5.large
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.large
      - m3.medium
      - m3.large
      - m3.xlarge
      - m4.large
      - m4.xlarge
      - m5.large
      - m5.xlarge
    Description: Enter the instance type for the application server. Default is t2.medium.
  Environment:
    Description: Enter the Environment
    Type: String
    ConstraintDescription: Must be a valid string.
  PEMFileName:
    Description: Enter the PEM file name
    Type: String
    Default: UAT
    ConstraintDescription: Must be a valid string.
Resources:
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: VPC
  EIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'FrontendInstance1'
      EIP: !Ref 'EIP'
  FrontendInstance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp2
            Encrypted: 'true'
      ImageId: !FindInMap 
        - Constants
        - AMI
        - Frontend1
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          DeleteOnTermination: 'true'
          GroupSet:
            - Fn::ImportValue:
                Fn::Sub: "${BaseStackName}-FrontendSecurityID"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${BaseStackName}-Subnet1ID"
          PrivateIpAddress: 192.168.1.10
      InstanceType: !Ref FrontendRoutingInstanceType
      KeyName: !Ref PEMFileName
      Tags:
        - Key: Name
          Value: !Sub ${BaseStackName}-Frontend-1-A
        - Key: Environment
          Value: !Sub ${BaseStackName}
        - Key:  Lifecycle
          Value: Daily
  EngineInstance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp2
            Encrypted: 'true'
      ImageId: !FindInMap 
        - Constants
        - AMI
        - RoutingServerAMI
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          DeleteOnTermination: 'true'
          GroupSet:
            - Fn::ImportValue:
                Fn::Sub: "${BaseStackName}-EngineSecurityID"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${BaseStackName}-Subnet1ID"
          PrivateIpAddress: 192.168.1.21
      InstanceType: !Ref EngineInstanceType
      KeyName: !Ref PEMFileName
      Tags:
        - Key: Name
          Value: !Sub ${BaseStackName}-Engine-1-A
        - Key: Environment
          Value: !Sub ${BaseStackName}
        - Key:  Lifecycle
          Value: Daily
  EngineInstance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp2
            Encrypted: 'true'
      ImageId: !FindInMap 
        - Constants
        - AMI
        - RoutingServerAMI
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          DeleteOnTermination: 'true'
          GroupSet:
            - Fn::ImportValue:
                Fn::Sub: "${BaseStackName}-EngineSecurityID"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${BaseStackName}-Subnet1ID"
          PrivateIpAddress: 192.168.1.22
      InstanceType: !Ref EngineInstanceType
      KeyName: !Ref PEMFileName
      Tags:
        - Key: Name
          Value: !Sub ${BaseStackName}-Engine-2-A
        - Key: Environment
          Value: !Sub ${BaseStackName}
        - Key:  Lifecycle
          Value: Daily
  EngineInstance3:
    Type: 'AWS::EC2::Instance'
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp2
            Encrypted: 'true'
      ImageId: !FindInMap 
        - Constants
        - AMI
        - RoutingServerAMI
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          DeleteOnTermination: 'true'
          GroupSet:
            - Fn::ImportValue:
                Fn::Sub: "${BaseStackName}-EngineSecurityID"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${BaseStackName}-Subnet1ID"
          PrivateIpAddress: 192.168.1.23
      InstanceType: !Ref EngineInstanceType
      KeyName: !Ref PEMFileName
      Tags:
        - Key: Name
          Value: !Sub ${BaseStackName}-Engine-3-A
        - Key: Environment
          Value: !Sub ${BaseStackName}
        - Key:  Lifecycle
          Value: Daily
  MongoInstance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp2
            Encrypted: 'true'
      ImageId: !FindInMap 
        - Constants
        - AMI
        - Mongo
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          DeleteOnTermination: 'true'
          GroupSet:
            - Fn::ImportValue:
                Fn::Sub: "${BaseStackName}-MongoSecurityID"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${BaseStackName}-Subnet1ID"
          PrivateIpAddress: 192.168.1.50
      InstanceType: !Ref MongoInstanceType
      KeyName: !Ref PEMFileName
      Tags:
        - Key: Name
          Value: !Sub ${BaseStackName}-Mongo-1-A
        - Key: Environment
          Value: !Sub ${BaseStackName}
        - Key:  Lifecycle
          Value: Daily
      